[character]
success_symbol = "[I](bold) [❯](bold red)"
error_symbol = "[I](bold) [❯](bold red)"
vicmd_symbol = "[N](bold) [❮](bold green)"

[gcloud]
disabled = true

# Needs: https://github.com/dmmulroy/jj-starship
[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

# Hide build-in modules when in a jj repo
[git_branch]
disabled = true

[git_status]
disabled = true
