#!/bin/sh

# Load dependencies (polybar, sxhkd, nitrogen)
# ---------------------------------------------
$HOME/.config/bspwm/autoload.sh

# Fix cursor issue
xsetroot -cursor_name left_ptr &

# bspwm settings
# ---------------------------------------------
bspc monitor -d I II III IV V

bspc config border_width    1
bspc config window_gap      14
bspc config top_padding     0
bspc config focused_border_color    '#ff0088'
bspc config normal_border_color     '#121212'

# Use this only of 144Hz screens
bspc config pointer_motion_interval 7ms
# Use this only of 60Hz
# bspc config pointer_motion_interval 17ms

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Peek state=floating
